// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXKJ86MUjALXZ8-k-nv3ezzd3oIfhFEyk',
    appId: '1:106813282442:web:28b1175ba1bd6ff3d1b573',
    messagingSenderId: '106813282442',
    projectId: 'fruit-hub-5124c',
    authDomain: 'fruit-hub-5124c.firebaseapp.com',
    storageBucket: 'fruit-hub-5124c.firebasestorage.app',
    measurementId: 'G-1Y3ZL4QSPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUKqYGB5QGCiaoBmjxMq2KAPCNxrhf5-U',
    appId: '1:106813282442:android:16630be45f90e5e0d1b573',
    messagingSenderId: '106813282442',
    projectId: 'fruit-hub-5124c',
    storageBucket: 'fruit-hub-5124c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmJ1bvokRiMPUYmK5PA-qCfbZ4bLfyIhI',
    appId: '1:106813282442:ios:2700d3e8992505c3d1b573',
    messagingSenderId: '106813282442',
    projectId: 'fruit-hub-5124c',
    storageBucket: 'fruit-hub-5124c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmJ1bvokRiMPUYmK5PA-qCfbZ4bLfyIhI',
    appId: '1:106813282442:ios:2700d3e8992505c3d1b573',
    messagingSenderId: '106813282442',
    projectId: 'fruit-hub-5124c',
    storageBucket: 'fruit-hub-5124c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXKJ86MUjALXZ8-k-nv3ezzd3oIfhFEyk',
    appId: '1:106813282442:web:a9da335657a59aeed1b573',
    messagingSenderId: '106813282442',
    projectId: 'fruit-hub-5124c',
    authDomain: 'fruit-hub-5124c.firebaseapp.com',
    storageBucket: 'fruit-hub-5124c.firebasestorage.app',
    measurementId: 'G-NFY5XYTFYY',
  );
}
